---
- name: Converge
  hosts: all
  become: true
  become_method: sudo

  vars:
    haproxy_links:
      - httpd
    haproxy_ports:
      - 80:80

  roles:
    - { role: ansible-role-haproxy, tags: ['haproxy'] }

  tasks:
    - name: Start httpd
      docker_container:
        name: httpd
        restart_policy: always
        image: httpd:2.4
