---
on: [push]

name: Test

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: virtualenv molecule
      #- name: Install molecule version 2
      #  run: pip3 install "molecule[docker] <3"

      #- name: Run test
      #  run: molecule --debug test -s docker
